### ISSUE TITLE
Julia 1.1 breaks things

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/SymbolServer.jl#18]
I think the core reason is that the new Pkg stuff uses the type ``UUID`` throughout to represent uuids, whereas the old version used ``String``. And our internal data structures now are all mixed up.

I don't know what the best way out here is. One option would be to move our internal data structures all over to ``UUID``, but I don't know whether that would work on julia 1.0. Or we keep using ``String``, then we need to make sure we convert properly...

I do think we should keep supporting julia 1.0, given that it is the long term stable release.

@ZacLN any ideas?

**Comment by ZacLN** [comment]
Yes definitely try to support both, conversion doesn't seem too bad?. I'm away without laptop for another week but will have a look when I get back

**Comment by fredrikekre** [comment]
To support the old style you can just call `string` on the `UUID` since that will work on both versions.

**Comment by davidanthoff** [comment]
I think the main issue is that code like [this](https://github.com/JuliaEditorSupport/SymbolServer.jl/blob/be0681dc042cd9fad5bb33f45b1bc0cc16db0ea5/src/clientprocess/clientprocess_main.jl#L8) returns ``Dict``s where the key is ``UUID`` on julia 1.1, but ``String`` on julia 1.0. So we need to make sure that we actually also convert those dicts to be of type ``Dict{String,Whatever}``.

**Comment by tribut** [comment]
Should be fixed by #22

**Comment by davidanthoff** [comment]
Thanks @tribut!!
